### ISSUE TITLE
This video file cannot be played. (Error Code: 102630 & 246007)

### ISSUE THREAD

**Issue by caliboycoder** [dnyaneshpainjane/TataPlay-web#2]
@dnyaneshpainjane First of all, Thank you so much for building such a great script. 

For some reason, I am keep getting this error "This video file cannot be played. (Error Code: 102630 & 246007)".

I have followed instructions from [here](https://appuals.com/fix-error-loading-media-file-not-played-chrome/#:~:text=The%20issue%20mainly%20occurs%20when,use%20the%20H264%20video%20codec) but still can't make it to work. I have tried to logout and logged back in but still issue persists. 

Any suggestion would be appreciated. Thanks

**Comment by dnyaneshpainjane** [comment]
Have you deployed the script or running on localhost?

**Comment by caliboycoder** [comment]
Thanks for your reply @dnyaneshpainjane . I have deployed script on AWS ec2 Ubuntu(LAMP server) instance

**Comment by dnyaneshpainjane** [comment]
This might be error due to network or vpn connection or region of deployment
You can use 000webhost which is free and script work fine there

**Comment by drtiwarir** [comment]
Hi, can you please help me in guiding how to set it up on 000webhost ?
Your help is appreciated
Regards

**Comment by dnyaneshpainjane** [comment]
https://youtu.be/Z5Q_QBpueus
Use this video as guide
You can delete existing files inside public_html &
Upload all the files of this repo inside public_html folder (keep folder structure same)

**Comment by drtiwarir** [comment]
Thanks for your reply.
I have followed the youtube guide but I am facing the same issue as before. The login page loads, but then nothing happens, I mean it gets stuck there.
<img width="1677" alt="Screenshot 2023-03-01 at 6 37 48 pm" src="https://user-images.githubusercontent.com/68334674/222075247-d6d51fa1-7468-4a6a-b075-987587b24c5d.png">

Am I doing something wrong or there is an issue with the script.
Please advice.
Regards

**Comment by drtiwarir** [comment]
Fixed it, now working.
Thanks

**Comment by dnyaneshpainjane** [comment]
I have modfifed the player script
try using new scripts
too many clicks may cause error in video player wait for sometime ahe try again playing channel
